- hosts: '{{ server | default("hadoop_all") }}'
  roles:
    - { role: common, common_config_hostname: True }
    - cdh5_spark

- hosts: '{{ server | default("hadoop_slave:hadoop_client") }}'
  roles:
    - { role: common, common_config_hostname: True }
    - gcc_gfortran
    - openblas

- hosts: '{{ server | default("hadoop_client") }}'
  roles:
    - { role: common, common_config_hostname: True }
    - openjdk
    - scala
    - sbt
    - activator_mini

- hosts: '{{ server | default("hadoop_other") }}'
  roles:
    - { role: common, common_config_hostname: True }
    - openjdk
    - scala
    - cdh5_sparkhistory

# vim: et ts=2 sw=2
