# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "hd-kafka01" do |config|
        config.vm.box = "centos/7"
        config.vm.network :private_network, ip: "192.168.33.21"
        config.vm.hostname = "hd-kafka01"
  end

  config.vm.define "hd-kafka02" do |config|
        config.vm.box = "centos/7"
        config.vm.network :private_network, ip: "192.168.33.22"
        config.vm.hostname = "hd-kafka02"
  end

  config.vm.define "hd-kafka03" do |config|
        config.vm.box = "centos/7"
        config.vm.network :private_network, ip: "192.168.33.23"
        config.vm.hostname = "hd-kafka03"
  end

  config.vm.define "hd-kafka04" do |config|
        config.vm.box = "centos/7"
        config.vm.network :private_network, ip: "192.168.33.24"
        config.vm.hostname = "hd-kafka04"
  end
end
